- hosts: all
  
  become: yes 
  tasks:

  # Install Docker
 
  - name: Docker | install prerequisites
    apt:
      name:
        - docker.io
      update_cache: yes

  - name: Docker | add user permissions
    shell: "usermod -aG docker {{ ansible_env.SUDO_USER }}"

  - name: Docker | Reset ssh connection for changes to take effect
    meta: "reset_connection"

  # Installs Docker SDK
 
  - name: Python3 | install python package manager
    apt:
      name: python3-pip
  
  - name: Python sdk | installation
    become_user: "{{ ansible_env.SUDO_USER }}"
    pip:
      name:
        - docker
        - docker-compose
  
  # Docker-compose with Jenkins in it

- name: Jenkins Container Installation
  hosts: all
  tasks:

    - name: Docker-compose | copying yaml file
      copy:
       src: JenkinsCompose/
       dest: tmp/

    - name: Docker-compose | deploying
      docker_compose:
        project_src: tmp/
        state: present

  # AWS CLI Installation

- name: AWS CLI installation and configurations
  hosts: all
  become: yes
  #remote_user: '{{ user }}'
  
  vars_files:
    - vars/vars.yaml

  pre_tasks:
    - name: apt-get update
      apt: update_cache=yes

    - name: AWS | install awscli
      pip: name=awscli

    - name: AWS | Assures dir exists
      file: path="~/.aws" state=directory

    - name: AWS | create credentials
      template:
        src: aws_credentials.tpl
        dest: "~/.aws/credentials"