Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2004"
 # config.vm.box_version = "1.0.282"

  # config.vm.box_download_insecure=true

  config.vm.network "public_network", bridge: "BRIDGE" # ip: "192.168.56.103"

  config.vm.synced_folder '.', '/vagrant', disabled: true #turns off synced directory for successful running from win11 wsl

  config.vm.provider "virtualbox" do |v|
   # v.gui = true #launches gui
    v.memory = "4096"
    v.cpus = 4
  end

 # Run Ansible from the Vagrant Host

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "install_docker_plbook.yaml" #docker, docker-compose installation
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "docker_compose_plbook.yaml" #launch jenkins in docker container
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "creating_jenkins_user.yaml" #creates jenkins user
  end

end