Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"
  config.vm.box_version = "1.0.282"
  config.vm.box_download_insecure=true

  config.vm.network "public_network", ip: "192.168.0.101"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end

 # Run Ansible from the Vagrant Host

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "install_docker_plbook.yaml" #docker, docker-compose installation
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "docker_compose_plbook.yaml" #launch jenkins in docker container
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "creating_jenkins_user.yaml" #creates jenkins user
  end

end