Vagrant.configure("2") do |config|
    config.vm.box = "hashicorp/bionic64"
    config.vm.provision "ansible", playbook: "ubuntu.yml"
    config.vm.network "public_network", ip: "192.168.0.101"
    config.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
    end
end