---

#RUN: `ansible-playbook create_jenkins_container.yaml --extra-vars "container_name=jenkins"`
#see: https://github.com/jenkinsci/docker/blob/master/README.md
#NOTE: You'll have to browse to the jenkins_home directory on your machine 
# to find the admin password (`docker volume inspect jenkins_home`)
#NOTE: This is intended to be run with an image built using the build_jenkins_image.yaml playbook

- hosts: all #127.0.0.1
  #connection: local
  tasks:
  - name: Create Docker Jenkins Container
    docker_container:
      name: "jenkins"
      image: jenkins-docker
      ports:
       - "8080:8080"
       - "50000:50000"
      volumes:
       - "jenkins_home:/var/jenkins_home"
       - "/var/run/docker.sock:/var/run/docker.sock"
      state: started