Vagrant.configure("2") do |config|
    config.vm.box = "hashicorp/bionic64"
   # config.vm.provision "ansible", playbook: "ubuntu.yml"
    config.vm.network "public_network", ip: "192.168.0.101"
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
    end
 
   # Run Ansible from the Vagrant Host
    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "install_docker.yaml" #docker installation
      ansible.playbook = "docker-compose.yaml"
    end
  
end