- name: docker-compose with jenkins
  hosts: all
  tasks:

  - name: copy docker-compose.yaml
    copy:
     src: DOCKER/
     dest: tmp/

  - name: deploy docker-compose
    docker_compose:
      project_src: tmp/
      state: present