- name: Setup Terraform on New Ubuntu 20.04 System
  hosts: all
  gather_facts: true

  tasks:
    - name: Update the APT Package Cache
      become: true
      apt:
        update_cache: true
        cache_valid_time: 3600
 
    - name: Adding the signing key
      become: true
      apt_key:
        url: "https://apt.releases.hashicorp.com/gpg"
        state: present
    
    - name: Adding the Hashicorp Repo to Ubuntu
      become: true
      apt_repository:
        repo: "deb [arch=amd64] https://apt.releases.hashicorp.com focal main"
        state: present

    - name: Install software from standard repos and hashicorp
      become: true
      package:
        name:
          # - docker.io
          - gnupg
          - software-properties-common
          - curl
          - terraform

    - name: Add the local USER to the Docker group
      become: true
      user:
        name: "{{ lookup('env', 'USER') }}"
        groups: docker
        append: true

    # - name: Cloning git repository
    #   git:
    #     repo: "https://github.com/marinaimeninnik/FinalProject.git"
    #     dest: "{{ lookup('env', 'HOME') }}/FinalProject"
    #     version: main

    # - name: Creating the directory for terraform project
    #   file:
    #     path: "{{ lookup('env', 'HOME') }}/terraform/"
    #     state: directory

    # - name: Creating the web directory to store content
    #   file:
    #     path: "{{ lookup('env', 'HOME') }}/terraform/web"
    #     state: directory