#!/bin/bash 

# based on https://tfswitch.warrensbox.com/Continuous-Integration/

echo "Installing tfswitch locally"

# Get the installer on to your machine

apt update

apt-get install -y wget

wget -N -c https://raw.githubusercontent.com/warrensbox/terraform-switcher/release/install.sh

# Make installer executable
chmod 755 install.sh

echo --------------working directory is $pwd

# Install tfswitch in a location you have permission
./install.sh -b $pwd/.bin

# set custom bin path
CUSTOMBIN=$pwd/.bin

#Add custom bin path to PATH environment
export PATH=$CUSTOMBIN:$PATH

#$CUSTOMBIN/tfswitch -b $CUSTOMBIN/terraform

tfswitch -b $CUSTOMBIN/terraform 1.3.8 #0.11.7

terraform $*